model_list:
  # ── ALIBABA / QWEN CODING PLAN ──────────────────────────────
  - model_name: ali-qwen3.5-plus
    litellm_params:
      model: openai/qwen3.5-plus
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-qwen3-max-2026-01-23
    litellm_params:
      model: openai/qwen3-max-2026-01-23
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-qwen3-coder-next
    litellm_params:
      model: openai/qwen3-coder-next
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-qwen3-coder-plus
    litellm_params:
      model: openai/qwen3-coder-plus
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-glm-5
    litellm_params:
      model: openai/glm-5
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-glm-4.7
    litellm_params:
      model: openai/glm-4.7
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-kimi-k2.5
    litellm_params:
      model: openai/kimi-k2.5
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY

  - model_name: ali-MiniMax-M2.5
    litellm_params:
      model: openai/MiniMax-M2.5
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/ALIBABA_CODING_API_KEY
